server.port=8080
server.forward-headers-strategy=native
spring.application.name=prod-eng-service
mongodb.connection.url=${MONGODB_CONNECTION_URL:mongodb://root:example@localhost:27017}
mongodb.database=${MONGODB_DATABASE:prod-eng}

spring.security.filter.order=10
spring.data.mongodb.auto-index-creation=true

prodeng.jwtSecret=${JWT_SECRET:e415546a1312fe62876c3431dc8caeb604a7876238485d9d14071108ce5adcce74b3679968da87984568cfd8494976b401e1cc880c6c4c7fa706cec3a3a045c9}
prodeng.jwtExpirationMs=7200000
prodeng.adminPassword=admin

management.endpoints.web.exposure.include=info,health,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
